version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "build(deps): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "build(ci): "
