import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Kapper',
  description: 'A lightweight, Dapper-inspired ORM for Kotlin and the JVM',
  base: '/kapper/',
  ignoreDeadLinks: [
    // Ignore all API documentation links (generated by dokka)
    (url, context) => {
      // Ignore any link within API documentation
      if (context?.includes('/api/')) {
        return true
      }
      // Ignore specific API link patterns
      return /^\.\/\.\./.test(url) ||                    // relative parent/ancestor links
             /^\.\/net\.samyn\.kapper/.test(url) ||      // package links
             /^\.\/-/.test(url)                          // dash-prefixed class links
    }
  ],
  
  head: [
    ['link', { rel: 'icon', href: '/kapper/favicon.ico' }]
  ],

  themeConfig: {
    logo: '/kapper-logo-small.png',
    
    nav: [
      { text: 'Guide', link: '/guide/' },
      { text: 'Examples', link: '/examples/' },
      { text: 'Performance', link: '/performance/' },
      { text: 'API Reference', link: '/api/' },
      { text: 'Blog', link: '/blog/' },
      { 
        text: 'v1.6.1', 
        items: [
          { text: 'Changelog', link: '/changelog' },
          { text: 'Migration Guide', link: '/guide/migration' }
        ]
      }
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/guide/' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Quick Start', link: '/guide/quick-start' }
          ]
        },
        {
          text: 'Core Concepts',
          items: [
            { text: 'Philosophy', link: '/guide/philosophy' },
            { text: 'Basic Usage', link: '/guide/basic-usage' },
            { text: 'Queries', link: '/guide/queries' },
            { text: 'Mapping', link: '/guide/mapping' },
            { text: 'Transactions', link: '/guide/transactions' }
          ]
        },
        {
          text: 'Advanced',
          items: [
            { text: 'Coroutines', link: '/guide/coroutines' },
            { text: 'Performance Tuning', link: '/guide/performance-tuning' },
            { text: 'Database Support', link: '/guide/database-support' }
          ]
        }
      ],
      '/blog/': [
        {
          text: 'Blog Posts',
          items: [
            { text: 'All Posts', link: '/blog/' },
            { text: 'Kapper 1.5: Record Support', link: '/blog/05_kapper_1-5_records_support' },
            { text: 'Kapper Benchmarks', link: '/blog/04_kapper_benchmarks' },
            { text: 'Kapper 1.3: Flow Support', link: '/blog/03_kapper_1-3_supports_flows' },
            { text: 'Coroutine Support in Kapper 1.1', link: '/blog/02_coroutine_support' },
            { text: 'Kapper Release', link: '/blog/01_kapper_release' }
          ]
        }
      ],
      '/examples/': [
        {
          text: 'Kotlin Examples',
          items: [
            { text: 'Basic CRUD', link: '/examples/kotlin/basic-crud' },
            { text: 'Advanced Queries', link: '/examples/kotlin/advanced-queries' },
            { text: 'Transactions', link: '/examples/kotlin/transactions' },
            { text: 'Coroutines', link: '/examples/kotlin/coroutines' }
          ]
        },
        {
          text: 'Java Examples',
          items: [
            { text: 'Basic CRUD', link: '/examples/java/basic-crud' },
            { text: 'Records Support', link: '/examples/java/records' }
          ]
        },
        {
          text: 'Use Cases',
          items: [
            { text: 'vs Hibernate', link: '/examples/comparisons/hibernate' },
            { text: 'vs Ktorm', link: '/examples/comparisons/ktorm' },
            { text: 'Migration Guide', link: '/examples/migration' }
          ]
        }
      ],
      '/performance/': [
        {
          text: 'Benchmarks',
          items: [
            { text: 'Overview', link: '/performance/' },
            { text: 'vs Competitors', link: '/performance/comparisons' },
            { text: 'Historical Data', link: '/performance/history' }
          ]
        }
      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/driessamyn/kapper' }
    ],

    footer: {
      message: 'Released under the Apache 2.0 License.',
      copyright: 'Copyright © 2023-present Dries Samyn'
    },

    search: {
      provider: 'local'
    },

    editLink: {
      pattern: 'https://github.com/driessamyn/kapper/edit/main/docs/:path',
      text: 'Edit this page on GitHub'
    }
  }
})