name: Publish JAR to Maven Central
on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v4.4.4
      - name: History
        run: git --no-pager log -n 100 --oneline
      - name: Tags
        run: git show-ref --tags
      - name: Print version
        run: ./gradlew printSemVersion --info
      - name: Run checks
        run: ./gradlew check
      - name: Show changes
        run: git status
      - name: Untracked changes
        run: git ls-files . --exclude-standard --others
      - name: Publish package
        env:
          GH_USER: driessamyn
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: ./gradlew :kapper:deployCentralPortal :kapper-coroutines:deployCentralPortal --info
